front_core:
    resource: "@FrontCoreBundle/Resources/config/routing.yml"
    prefix:   /

front_security:
    resource: "@FrontSecurityBundle/Resources/config/routing.yml"
    prefix:   /

ro_app:
    resource: "@FrontAppBundle/Resources/config/routing.yml"
