security:
    encoders:
         Front\SecurityBundle\Security\User\WebserviceUser: sha512
         Symfony\Component\Security\Core\User\User:
             algorithm: bcrypt
             cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_COMPANY_ADMIN: ROLE_COMPANY_ADMIN
        ROLE_AMBASSADOR: ROLE_AMBASSADOR

    providers:
        webservice:
            id: app.webservice_user_provider
#        in_memory:
#            memory:
#                users:
#                    ovidiu:
#                        password: $2a$12$77DgS/ul7u4nEC1./69ZP.CwyQ5uCzFPMMuy.m19yIgDb.u0WMe2G
#                        roles: 'ROLE_USER'
#                    remus:
#                        password: $2a$12$77DgS/ul7u4nEC1./69ZP.CwyQ5uCzFPMMuy.m19yIgDb.u0WMe2G
#                        roles: 'ROLE_USER'


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/secured/
            simple_form:
                authenticator: app.security.api_user_authenticator
                check_path: /secured/login_check
                login_path: /secured/login/
                default_target_path: /secured/dashboard/
                always_use_default_target_path: true
                use_referer: false
                require_previous_session: false
#            http_basic:
#                realm: 'Login'
#                provider: in_memory
            logout:
                path:   /secured/logout
                target: /
                invalidate_session: true
            anonymous: ~

    access_control:
        - { path: ^/secured/account-details/, role: ROLE_USER }
        - { path: ^/secured/dashboard/, role: ROLE_USER }
        - { path: ^/secured/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured/check-facebook, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured/check-google, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/index, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }