# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.api_service:
        class: Front\DataBundle\Services\ApiService
        arguments: ["@service_container"]

    app.facebook_authentication:
        class: Front\SecurityBundle\Services\FacebookAuthentication
        arguments: ["@service_container"]

    app.user_session:
        class: Front\SecurityBundle\Services\UserSession
        arguments: ["@session", "@request_stack"]

    #provider1
    app.security:
        class: Front\SecurityBundle\Services\SecurityService
        arguments: ["@service_container"]

    #provider2
    app.webservice_user_provider:
        class: Front\SecurityBundle\Security\User\WebserviceUserProvider
        arguments: ["@app.api_service"]

    app.security.api_user_authenticator:
        class: Front\SecurityBundle\Security\Authenticator\ApiAuthenticator
        arguments: ["@app.api_service", "@app.security", "@app.user_session", "@request_stack", "%api_address%", "@security.password_encoder"]
