front_app_category:
    resource: "@FrontAppCategoryBundle/Resources/config/routing.yml"
    prefix:   /

front_app_ad:
    resource: "@FrontAppAdBundle/Resources/config/routing.yml"
    prefix:   /

front_app_data:
    resource: "@FrontAppDataBundle/Resources/config/routing.yml"
    prefix:   /

front.home_page.index:
    path: /
    defaults:
      _controller: 'FrontAppAppBundle:HomePage:index'